<?php
return array(
    // Package index URLs. Add more as needed.
    'package_index_urls' => array(
        'https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/arduino/package_m5stack_index.json',
        'https://espressif.github.io/arduino-esp32/package_esp32_index.json',
    ),

    // Output directory for collected JSON files.
    'output_dir' => __DIR__ . '/out',

    // Work directory for downloads/extraction.
    'work_dir' => sys_get_temp_dir() . '/arduiono-variants-work',

    // Mapping from build.mcu to SOC_GPIO_PIN_COUNT.
    // If build.mcu is not present here, the script will stop with an error.
    'mcu_gpio_counts' => array(
        'esp32' => 40,
        'esp32s2' => 47,
        'esp32s3' => 49,
        'esp32c2' => 21,
        'esp32c3' => 22,
        'esp32c5' => 29,
        'esp32c6' => 31,
        'esp32c61' => 30,
        'esp32h2' => 28,
        'esp32h21' => 26,
        'esp32h4' => 40,
        'esp32p4' => 55,
        'esp32s31' => 62,
    ),

    // Ignore pin names in header generation.
    'header_ignore_names' => array(
        '_LORA_LNA_ENABLE',
        '_LORA_ANTENNA_SWITCH',
        '_LORA_ENABLE',
        '_POWEROFF',
        '_GROVE_POWER_EN',
        '_VIN_DETECT',
        '_LCD_RESET',
        '_LCD_BACKLIGHT',
        '_LED_BUILTIN',
        '_KEY1',
        '_KEY2',
        'ETH_PHY_KSZ8081',
        'ETH_CLOCK_GPIO0_IN',
        'ETH_PHY_LAN8720',
        'SDMMC_FREQ_DEFAULT',
        'ETH_CLOCK_GPIO17_OUT',
        'ETH_CLOCK_GPIO0_OUT',
        'ETH_PHY_DP83848',
        'ETH_PHY_TLK110',
        'EMAC_CLK_EXT_IN',
        'ST7789',
        'I2S_CHANNEL_FMT_ONLY_LEFT',
        'TFT_BGR',
        'WF4_S1_PIN',
        'SPI_CS1',
        'SPI3_HOST',
        'ETH_PHY_W5500',
        'SPI2_HOST',
        'ETH_PHY_LAN867X',
        'const',
        'GRB',
        'WS2812',
        'ETH_PHY_RTL8201',
        'HIGH',
        'LOW',
        'SDA',
        'SCL',
        'SS',
        'MOSI',
        'MISO',
        'SCK',
        'A0',
        'VSPI',
        'HSPI',
        'UP_BTN_MASK',
        'MENU_BTN_MASK',
        'BACK_BTN_MASK',
        'DOWN_BTN_MASK',
        'ACC_INT_MASK',
        'BTN_PIN_MASK',
        'LED_COLOR_ORDER_RGB',
        'NOT_A_PIN',
        'LED_COLOR_ORDER_GRB',
        'RGB_BRIGHTNESS',
        'LED_BUILTIN',
        'dammy',
        'dammy',
        'dammy',
        'dammy',
    ),

    // HTTP settings.
    'http_user_agent' => 'arduiono-variants-collector/1.0',
    'http_timeout_sec' => 60,
);
